### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by spotlesscoder** [Jon-Peppinck/linkedin-clone#2]
when I try to run the feedcontroller tests, I get the following error: 

```
  ● Test suite failed to run

    Cannot find module 'src/chat/models/conversation.entity' from 'auth/models/user.entity.ts'

    Require stack:
      auth/models/user.entity.ts
      feed/models/post.entity.ts
      feed/services/feed.service.ts
      feed/controllers/feed.controller.ts
      feed/controllers/feed.controller.spec.ts

      10 | import { Role } from './role.enum';
      11 | import { FriendRequestEntity } from './friend-request.entity';
    > 12 | import { ConversationEntity } from 'src/chat/models/conversation.entity';
         | ^
      13 | import { MessageEntity } from 'src/chat/models/message.entity';
      14 |
      15 | @Entity('user')

      at Resolver.resolveModule (../node_modules/jest-resolve/build/resolver.js:311:11)
      at Object.<anonymous> (auth/models/user.entity.ts:12:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.227 s
Ran all test suites matching /\/home\/user\/linkedin-clone\/api\/src\/feed\/controllers\/feed.controller.spec.ts/i with tests matching "FeedController".
```

How can I fix that?

**Comment by Jon-Peppinck** [comment]
Imports need to be relative (../../) instead of @src
